### ISSUE TITLE
The color hex in the tooltip is unreadable for dark colors

### ISSUE THREAD

**Issue by aaronhowser1** [MehVahdJukaar/JustEnoughEffectDescriptions#1]
![image](https://user-images.githubusercontent.com/15698722/135565098-43a29c85-1356-4e21-9a73-2e393135fa30.png)

This thing. For dark colors, it blends into the tooltip background. Maybe instead of coloring the hex code, it should be white and then have a colored square (■) after it?

**Comment by MehVahdJukaar** [comment]
Well that's the actual color that's getting used by the effect. Usually mods that just use black don't intend for the color to be viewed and judging by those icons I'm guessing that that is the case. I've set it so hidden technical effects like those will no longer show up at all and will be completely ignored

**Comment by Fuzss** [comment]
You can simply brighten the color when it’s too dark, this is how I do it in Stylish Effects (feel free to copy the class): https://github.com/Fuzss/stylisheffects/blob/1.19/Common/src/main/java/fuzs/stylisheffects/client/util/ColorUtil.java

**Comment by MehVahdJukaar** [comment]
Oh I already had a Color util class that did that [here](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/blob/master/src/main/java/net/mehvahdjukaar/jeed/utils/HSLColor.java)
Thing is I'm only using it to change the Color in the JEI page as I wanted this to be the one in the tooltip to be the exact one used in the effect. Guess I'll close this
