### ISSUE TITLE
Typo on your end

### ISSUE THREAD

**Issue by zachsai** [MehVahdJukaar/JustEnoughEffectDescriptions#10]
![image](https://user-images.githubusercontent.com/63996164/162552595-81f11579-6255-48c4-b164-c77540de0238.png)
typo for the effect description for farmers delight
andHunger with no spaces.
should say in proper english:

Removes and grants immunity to: Slowness, Hunger, and Weakness

**Comment by MehVahdJukaar** [comment]
I believe this was fixed at some point so I'll close
