### ISSUE TITLE
Effect icons are off-centered

### ISSUE THREAD

**Issue by wafflebot2143** [MehVahdJukaar/JustEnoughEffectDescriptions#12]
![2022-06-06_23 24 26](https://user-images.githubusercontent.com/99057685/172289561-739d3632-1a88-4cef-963a-6cb696a02c0c.png)
The icons for effects are incorrectly aligned, as you can see in the above example. If it helps anyhow, I use REI instead of JEI and play on 1.18.2. Any assistance would be appreciated.

**Comment by MehVahdJukaar** [comment]
Well looks like REI fixed up that part of their code. I had set in some specific check that would offset those icons when REI was installed since they had the opposite issue back then. Now that it has been fixed they are offset the other way of course

**Comment by wafflebot2143** [comment]
Thanks for the reply. Is there anything I need to do or is it fixed in the release?

**Comment by wafflebot2143** [comment]
Never mind, I just checked the Curseforge releases tab and I can see that you fixed it. Thanks!
