### ISSUE TITLE
Effect icons are doubled with REI

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/JustEnoughEffectDescriptions#21]
When this mod is used with Roughly Enough Items and an effect description is viewed, the effect icon is rendered twice, overlapping itself.
![2022-10-14_20 00 24](https://user-images.githubusercontent.com/69029346/196014796-cedc2c46-66bf-490f-a28c-1f01cd5372cd.png)

**Comment by MehVahdJukaar** [comment]
This only apeared recently. REI is supposed to mimic JEI behaviour and support it's add-ons so the issue is on their side
