### ISSUE TITLE
Some modded potion effect descriptions fail to load

### ISSUE THREAD

**Issue by RobertHDPotatoes** [MehVahdJukaar/JustEnoughEffectDescriptions#3]
Although there are entries in the lang file for the potion effects for the mods; Cofh_core, mowzies mobs (and possibly more - those were the only two I tested), their entries fail to actually show in game and instead their descriptions are "No description available."

Minecraft version: 1.16.5
JEED version: jeed-1.16.5-1.5
JEI version: jei-1.16.5-7.7.1.136
COFH_CORE version: cofh_core-1.16.5-1.3.1
mowzies mobs: version: 1.5.19

This should be easily reproduced. If it cannot be reproduced let me know and I can provide my logs.
To reproduce:
1: Install JEI, JEED & CofhCore/Mowzies mobs. 
2: Load into a world, and give yourself an effect added from those mods. 
3: Click the effect icon to the left of your inventory.

**Comment by MehVahdJukaar** [comment]
should be fixed in 1.6. There were many typos there
