### ISSUE TITLE
[1.19.2] Overencumbering compat recipe missing effect

### ISSUE THREAD

**Issue by DelviousCrafts** [MehVahdJukaar/JustEnoughEffectDescriptions#31]
With the latest update to JEED there is an additional recipe in compact for supplementaries overencumbered effect. This recipe is missing the effect line causing an error thrown for recipe parsing when supplementaries is installed.

Versions:
Minecraft: 1.19.2
Forge: 43.2.10
JEI: 11.6.0.1015
JEED: 2.1.0
Supplementaries: 2.3.9

**Comment by kasperbjerby** [comment]
Sometimes i wonder if they even test stuff before pushing a update out

**Comment by MehVahdJukaar** [comment]
Test yes. With other mods no, not every time at least even if they are my own
