### ISSUE TITLE
Can't filter entries in REI

### ISSUE THREAD

**Issue by tikiMC** [MehVahdJukaar/JustEnoughEffectDescriptions#33]
When going into REI's custom manual filtering page and selecting everything to be hidden. The only entries that still appear are the JEED effects. There are a few effects that shouldn't be obtainable from Xaero's World and Minimap so it is frustrating to not be able to hide. I also tried JEED's config to hide effects, but that only seems to be for JEI as it didn't work with REI.

![2023-05-09_03 03 40](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/assets/70704691/e6f07349-f679-40d8-ae47-afe7df9a9492)
![2023-05-09_03 03 55](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/assets/70704691/bbde1147-e4ae-4add-bf99-6824e2318abb)

**Comment by MehVahdJukaar** [comment]
are you using the latest version right?

**Comment by tikiMC** [comment]
Yes, it doesn't work on 2.1.2

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by tikiMC** [comment]
thank you for the quick fix I appreciate it!
