### ISSUE TITLE
[BUG] Beacon text rendering doubling.

### ISSUE THREAD

**Issue by KostromDan** [MehVahdJukaar/JustEnoughEffectDescriptions#40]
![image](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/assets/90044015/34d51172-4263-49fe-8eb1-82278497d9e5)
M-Tech modpack 1.19.2 1.6.5
I'll tempoary remove this mod until it fixed.

**Comment by TBlazeWarriorT** [comment]
+1
Same issue on 1.20.1
No settings fix it
Looks horrible

Spent 1 hour figuring out and recompiling the mod with the beacon interface extension commented out
