### ISSUE TITLE
When description is too long, it dupes the description blocks

### ISSUE THREAD

**Issue by WelpSTudent** [MehVahdJukaar/JustEnoughEffectDescriptions#8]
![image](https://user-images.githubusercontent.com/63996164/158532488-96068a87-2f5c-44e8-b024-844527a06760.png)

**Comment by MehVahdJukaar** [comment]
That's intended. Works the same as jei info tab. However I have to say its probably meant to work best with bigger gui scales since in most of those jei only displays one page at a time

**Comment by WelpSTudent** [comment]
That was my thought, maybe there is a way to make it look more visually pleasing?
